inventmanage/inventapp/urls.py
from django.urls import path
from inventapp import views

urlpatterns = [
    path('saveObject/<str:objectType>/',views.saveObject,name='saveObject'),
    path('updateObject/<str:objectType>/<str:objectId>',views.updateObject,name='updateObject'),
    path('showObjects/<str:objectType>',views.showObjectList, name='showObjects'),
    path('showObjectDetails/<str:objectType>/<str:objectId>',views.showObjectDetail,name='showObjectDetail'),
    path('modelObjects/<str:objectType>',views.modelObjects,name='addEditObjects'),
    path("register/", views.register, name="register"),
    path("login/", views.user_login, name="user_login"),
    path('logout/', views.user_logout, name='logout'),
]

inventmanage/inventmanage/urls.py
from django.contrib import admin
from django.urls import path, include
from inventapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.index, name="index"),
    path('admin/', admin.site.urls),
    path('', include('inventapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventmanage/inventapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

# Create your models here.

class Inventory(models.Model):
    inv_id = models.PositiveIntegerField()
    inv_name = models.CharField(max_length=100)
    inv_location = models.CharField(max_length=100)

    def __str__(self):
        return self.inv_name

class Item(models.Model):
    item_id = models.PositiveIntegerField()
    item_stock = models.PositiveIntegerField()
    item_minimum_required = models.PositiveIntegerField()
    item_name = models.CharField(max_length=100)
    inv = models.PositiveIntegerField()

    def __str__(self):
        return self.item_name

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    users_id = models.PositiveIntegerField(default=301)
    mobile_regex = RegexValidator(regex=r'^(?:(?:\+|0{0,2})91(\s*[\ -]\s*)?|[0]?)?[6789]\d{9}|(\d[ -]?){10}\d$', message="Please Enter A Valid Mobile Number!")
    user_mobile = models.CharField(validators=[mobile_regex], max_length=10)
    inv_id = models.ForeignKey(Inventory, on_delete = models.CASCADE, related_name='inventory_user')

    def __str__(self):
        return self.user.username

class Customer(models.Model):
    customer_id = models.PositiveIntegerField()
    customer_name = models.CharField(max_length=100)
    mobile_regex = RegexValidator(regex=r'^(?:(?:\+|0{0,2})91(\s*[\ -]\s*)?|[0]?)?[6789]\d{9}|(\d[ -]?){10}\d$', message="Please Enter A Valid Mobile Number!")
    customer_mobile = models.CharField(validators=[mobile_regex], max_length=10)
    customer_email = models.EmailField()
    users = models.PositiveIntegerField()

    def __str__(self):
        return self.customer_name

class Payment(models.Model):
    pay_id = models.PositiveIntegerField()
    pay_date = models.DateField()
    pay_amount = models.PositiveIntegerField()
    customer = models.PositiveIntegerField()
    users = models.PositiveIntegerField()

    def __str__(self):
        return str(self.pay_id)

class Orders(models.Model):
    order_id = models.PositiveIntegerField()
    pay = models.PositiveIntegerField()
    customer = models.PositiveIntegerField()
    users = models.PositiveIntegerField()
    item = models.PositiveIntegerField()

    def __str__(self):
        return str(self.order_id)

inventmanage/inventapp/forms.py
from django import forms
from .models import (User, UserProfile, Customer, Inventory, Item, Orders, Payment)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfile
        fields = ('user_mobile', 'inv_id', 'users_id')

inventmanage/inventapp/views.py
from django.shortcuts import render
from .models import *
from django.contrib.auth.models import User
from .forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import inspect
import inventapp.models as models
from inventapp.sqlqueries import *

modelNames = list()
for name, obj in inspect.getmembers(models, inspect.isclass):
    modelNames.append(name.lower())

# Create your views here.

def index(request):
    return render(request, "index.html", {"modelNames":modelNames,})

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('user_login'))

def register(request):

    registered = False
    username = "Customer"

    if request.method == "POST":
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        username = request.POST.get("username")
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
            return HttpResponseRedirect(reverse('user_login'))
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    cust_dict = {
        "registered" : registered,
        "user_form" : user_form,
        "profile_form" : profile_form,
        "username" : username,
    }
    return render(request, "authentication/registration.html", context = cust_dict)

def user_login(request):
    loginFailed = False
    if request.method == 'POST':
    # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')
        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check if the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                loginFailed = False
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            loginFailed = True
            return render(request, 'authentication/login.html', {'loginFailed' : loginFailed,})
    else:
        #Nothing has been provided for username or password.
        return render(request, 'authentication/login.html', {'loginFailed' : loginFailed,})

def getDBObject(objectType,caller,objectId=None):
        modelClass1 = globals()[objectType.title()]
        modelClass = 'inventapp_{}'.format(objectType)
        if caller == 'modelObjects':
            return model_objects(modelClass, objectId)
        elif caller == 'showObjectDetails':
            return show_object_details(modelClass, objectId)
        elif caller == 'showObjectList':
            return show_objects_list(modelClass)
        elif caller == 'saveObject':
            return modelClass1.objects.last()

def getContextObject(objectType,objectId=None):
        print('INSDE')
        if objectType == 'item':
            print('finside')
            inventory = Inventory.objects.all().only("inv_id")
            print(inventory)
            values = list()
            for x in inventory:
                values.append(x.inv_id)


            objectSet0 = {
                    'values':  values,
                    'targetControlID': 'id_inv',
                    }

            additionalObjects = {
                    'Item0':objectSet0,
                    }

            return additionalObjects #additionalObjects

        elif objectType == 'customer':
            print('finside')
            user = UserProfile.objects.all().only("users_id")
            print(user)
            values = list()
            for x in user:
                values.append(x.users_id)

            objectSet0 = {
                    'values':  values,
                    'targetControlID': 'id_users',
                    }

            additionalObjects = {
                    'Customer0':objectSet0,
                    }

            return additionalObjects #additionalObjects

        elif objectType == 'orders':
            print('finside')
            user = UserProfile.objects.all().only("users_id")
            print(user)
            values1 = list()
            for x in user:
                values1.append(x.users_id)

            payment = Payment.objects.all().only("pay_id")
            print(payment)
            values2 = list()
            for x in payment:
                values2.append(x.pay_id)

            item = Item.objects.all().only("item_id")
            print(item)
            values3 = list()
            for x in item:
                values3.append(x.item_id)

            customer = Customer.objects.all().only("customer_id")
            print(customer)
            values4 = list()
            for x in customer:
                values4.append(x.customer_id)

            objectSet0 = {
                    'values':  values1,
                    'targetControlID': 'id_users',
                    }
            objectSet1 = {
                    'values':  values2,
                    'targetControlID': 'id_pay',
                    }
            objectSet2 = {
                    'values':  values3,
                    'targetControlID': 'id_item',
                    }
            objectSet3 = {
                    'values':  values4,
                    'targetControlID': 'id_customer',
                    }

            additionalObjects = {
                    'Customer0':objectSet0,
                    'Customer1':objectSet1,
                    'Customer2':objectSet2,
                    'Customer3':objectSet3,
                    }

            return additionalObjects #additionalObjects

        elif objectType == 'payment':
            print('finside')
            user = UserProfile.objects.all().only("users_id")
            print(user)
            values1 = list()
            for x in user:
                values1.append(x.users_id)

            customer = Customer.objects.all().only("customer_id")
            print(customer)
            values4 = list()
            for x in customer:
                values4.append(x.customer_id)

            objectSet0 = {
                    'values':  values1,
                    'targetControlID': 'id_users',
                    }

            objectSet3 = {
                    'values':  values4,
                    'targetControlID': 'id_customer',
                    }

            additionalObjects = {
                    'Customer0':objectSet0,
                    'Customer3':objectSet3,
                    }

            return additionalObjects #additionalObjects

def modelObjects(request, objectType):
    print(modelNames)
    if 'edit' in request.GET:
        objectId = request.GET['objectId']
        objToUpdate = list(getDBObject(objectType,'modelObjects',objectId)[0][0])
        objectColumnList = getDBObject(objectType,'showObjectList')[1]
        fieldNames = [x[0] for x in objectColumnList]
        objDict = dict(zip(fieldNames, objToUpdate))
        context = {"objectType": objectType,
                "objectToUpdate":objDict,
                "modelNames":modelNames,
                "otherObjects":getContextObject(objectType),
        }

        templateFile = objectType+'Form.html'
        return render(request,templateFile, context)
    else: # if request is to add a new object
        context = {"objectType": objectType,
        "modelNames": modelNames,
        "otherObjects":getContextObject(objectType),
        }

        templateFile = objectType+'Form.html'
        return render(request,templateFile, context)

def updateObject(request,objectType,objectId):
    if request.POST:
        modelClass = 'inventapp_{}'.format(objectType)
        id = 'id'+'='+str(objectId)
        values = [id]
        if request.GET['operation'] == 'update':
            for key in request.POST:
                if key != 'csrfmiddlewaretoken':
                    if isinstance(request.POST[key], str):
                        values.append(key+"="+"'{}'".format(request.POST[key]))
                    else:
                        values.append(key+"="+str(request.POST[key]))
            print(values)
            update_object(modelClass, values, objectId)
        elif request.GET['operation'] == 'delete':
            delete_object(modelClass, objectId)

        context = {
        "objectType":objectType,
        "objectID":objectId,
        "Operation":request.GET['operation'],
        "modelNames":modelNames,
        }
        return render(request,"saveConfirmation.html",context)

def saveObject(request,objectType):
    if request.POST:
        modelClass = 'inventapp_{}'.format(objectType)
        id = getDBObject(objectType,'saveObject').id + 1
        values = [id]
        for key in request.POST:
            if key != 'csrfmiddlewaretoken':
                values.append(request.POST[key])
        print(values)
        save_object(modelClass, values)

        context = {
        "objectType":objectType,
        "objectID":values[0],
        "Operation":'add',
        "modelNames":modelNames,
        }

inventmanage/inventapp/templates/inventapp/customerForm.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block page_content %}
<section id="entry">
 <h1>Customer</h1>
 <form enctype="multipart/form-data" method="post">
   {% csrf_token %}
   <div class="form-group">
     <label for="id_customer_id"> Customer ID </label>
     <input type="number" name="customer_id" class="form-control" maxlength="60" required id="id_customer_id" />
   </div>
   <br>
   <div class="form-group">
     <label for="id_customer_name"> Customer Name </label>
     <input type="text" name="customer_name" class="form-control" maxlength="60" required id="id_customer_name" />
   </div>
   <br>
   <div class="form-group">
     <label for="id_customer_mobile"> Customer Mobile No. </label>
     <input type="text" name="customer_mobile" class="form-control" maxlength="10" required id="id_customer_mobile" />
   </div>
   <br>
   <div class="form-group">
     <label for="id_customer_email"> Customer Email </label>
     <input type="email" name="customer_email" class="form-control" maxlength="60" required id="id_customer_email" />
   </div>
   <br>
   <div class="form-group">
     <label for="octane">User ID</label>
     <select class="form-control" id="id_users" name="users">
       <option selected disabled>--Select One Option--</option>
     </select>
   </div>
   <br>

   {% if not objectToUpdate.id  %}
    <button formaction="/saveObject/{{objectType}}/" class="btn btn-primary" type="submit">Save</button>
    <a href="/showObjects/{{objectType}}" class="btn btn-primary" role="button">Cancel</a>
   {% else %}
    <button formaction="/updateObject/{{objectType}}/{{objectToUpdate.id}}?operation=update" class="btn btn-primary" type="submit"> Update </button>
    <button formaction="/updateObject/{{objectType}}/{{objectToUpdate.id}}?operation=delete" class="btn btn-primary" type="submit"> Delete </button>
    <a href="/showObjects/{{objectType}}" class="btn btn-primary" type="button">Cancel</a>
   {% endif %}
 </form>
 </section>
{% endblock %}

inventmanage/inventapp/templates/inventapp/index.html
{% extends "base.html" %}
{% block page_content %}
<h1 class="text-center" style="font-size:48px;">Welcome to RDX Inventory Management System</h1>
<img src="/media/images/img-inventory-control.png" width="50%" height="50%" class="rounded mx-auto d-block" alt="inventory management">
{% endblock %}

inventmanage/inventapp/templates/inventapp/inventoryForm.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block page_content %}
<section id="entry">
 <h1>Inventory</h1>
 <form enctype="multipart/form-data" method="post">
   {% csrf_token %}
   <div class="form-group">
     <label for="id_inv_id"> Inventory ID </label>
     <input type="number" name="inv_id" class="form-control" maxlength="60" required id="id_inv_id" />
   </div>
   <br>
   <div class="form-group">
     <label for="id_inv_name"> Inventory Name </label>
     <input type="text" name="inv_name" class="form-control" maxlength="60" required id="id_inv_name" />
   </div>
   <br>
   <div class="form-group">
     <label for="id_inv_location"> Inventory Location </label>
     <input type="text" name="inv_location" class="form-control" maxlength="60" required id="id_inv_location" />
   </div>
   <br>

   {% if not objectToUpdate.id  %}
    <button formaction="/saveObject/{{objectType}}/" class="btn btn-primary" type="submit">Save</button>
    <a href="/showObjects/{{objectType}}" class="btn btn-primary" role="button">Cancel</a>
   {% else %}
    <button formaction="/updateObject/{{objectType}}/{{objectToUpdate.id}}?operation=update" class="btn btn-primary" type="submit"> Update </button>
    <button formaction="/updateObject/{{objectType}}/{{objectToUpdate.id}}?operation=delete" class="btn btn-primary" type="submit"> Delete </button>
    <a href="/showObjects/{{objectType}}" class="btn btn-primary" type="button">Cancel</a>
   {% endif %}
 </form>
 </section>
{% endblock %}

inventmanage/inventapp/templates/inventapp/itemForm.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block page_content %}
<section id="entry">
 <h1>Item</h1>
 <form enctype="multipart/form-data" method="post">
   {% csrf_token %}
   <div class="form-group">
     <label for="id_item_id"> Item ID </label>
     <input type="number" name="item_id" class="form-control" maxlength="60" required id="id_item_id" />
   </div>
   <br>
   <div class="form-group">
     <label for="id_item_stock"> Item Stock </label>
     <input type="number" name="item_stock" class="form-control" maxlength="60" required id="id_item_stock" />
   </div>
   <br>
   <div class="form-group">
     <label for="id_item_minimum_required"> Minimum Item Required </label>
     <input type="number" name="item_minimum_required" class="form-control" maxlength="60" required id="id_item_minimum_required" />
   </div>
   <br>
   <div class="form-group">
     <label for="id_item_name"> Item Name </label>
     <input type="text" name="item_name" class="form-control" maxlength="60" required id="id_item_name" />
   </div>
   <br>
   <div class="form-group">
     <label for="octane">Inventory ID</label>
     <select class="form-control" id="id_inv" name="inv">
       <option selected disabled>--Select One Option--</option>
     </select>
   </div>
   <br>

   {% if not objectToUpdate.id  %}
    <button formaction="/saveObject/{{objectType}}/" class="btn btn-primary" type="submit">Save</button>
    <a href="/showObjects/{{objectType}}" class="btn btn-primary" role="button">Cancel</a>
   {% else %}
    <button formaction="/updateObject/{{objectType}}/{{objectToUpdate.id}}?operation=update" class="btn btn-primary" type="submit"> Update </button>
    <button formaction="/updateObject/{{objectType}}/{{objectToUpdate.id}}?operation=delete" class="btn btn-primary" type="submit"> Delete </button>
    <a href="/showObjects/{{objectType}}" class="btn btn-primary" type="button">Cancel</a>
   {% endif %}
 </form>
 </section>
{% endblock %}

inventmanage/inventapp/templates/inventapp/ordersForm.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block page_content %}
<section id="entry">
 <h1>Orders</h1>
 <form enctype="multipart/form-data" method="post">
   {% csrf_token %}
   <div class="form-group">
     <label for="id_order_id"> Order ID </label>
     <input type="number" name="order_id" class="form-control" maxlength="60" required id="id_order_id" />
   </div>
   <br>
   <div class="form-group">
     <label for="octane">Payment ID</label>
     <select class="form-control" id="id_pay" name="pay">
       <option selected disabled>--Select One Option--</option>
     </select>
   </div>
   <br>
   <div class="form-group">
     <label for="octane">Customer ID</label>
     <select class="form-control" id="id_customer" name="customer">
       <option selected disabled>--Select One Option--</option>
     </select>
   </div>
   <br>
   <div class="form-group">
     <label for="octane">User ID</label>
     <select class="form-control" id="id_users" name="users">
       <option selected disabled>--Select One Option--</option>
     </select>
   </div>
   <br>
   <div class="form-group">
     <label for="octane">Item ID</label>
     <select class="form-control" id="id_item" name="item">
       <option selected disabled>--Select One Option--</option>
     </select>
   </div>
   <br>

   {% if not objectToUpdate.id  %}
    <button formaction="/saveObject/{{objectType}}/" class="btn btn-primary" type="submit">Save</button>
    <a href="/showObjects/{{objectType}}" class="btn btn-primary" role="button">Cancel</a>
   {% else %}
    <button formaction="/updateObject/{{objectType}}/{{objectToUpdate.id}}?operation=update" class="btn btn-primary" type="submit"> Update </button>
    <button formaction="/updateObject/{{objectType}}/{{objectToUpdate.id}}?operation=delete" class="btn btn-primary" type="submit"> Delete </button>
    <a href="/showObjects/{{objectType}}" class="btn btn-primary" type="button">Cancel</a>
   {% endif %}
 </form>
 </section>
{% endblock %}

inventmanage/inventapp/templates/inventapp/paymentForm.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block page_content %}
<section id="entry">
 <h1>Payment</h1>
 <form enctype="multipart/form-data" method="post">
   {% csrf_token %}
   <div class="form-group">
     <label for="id_pay_id"> Payment ID </label>
     <input type="number" name="pay_id" class="form-control" maxlength="60" required id="id_pay_id" />
   </div>
   <br>
   <div class="form-group">
     <label for="id_pay_date"> Payment Date </label>
     <input type="date" name="pay_date" class="form-control" maxlength="60" required id="id_pay_date" />
   </div>
   <br>
   <div class="form-group">
     <label for="id_pay_amount"> Payment Amount </label>
     <input type="number" name="pay_amount" class="form-control" maxlength="60" required id="id_pay_amount" />
   </div>
   <br>
   <div class="form-group">
     <label for="octane">Customer ID</label>
     <select class="form-control" id="id_customer" name="customer">
       <option selected disabled>--Select One Option--</option>
     </select>
   </div>
   <br>
   <div class="form-group">
     <label for="octane">User ID</label>
     <select class="form-control" id="id_users" name="users">
       <option selected disabled>--Select One Option--</option>
     </select>
   </div>
   <br>

   {% if not objectToUpdate.id  %}
    <button formaction="/saveObject/{{objectType}}/" class="btn btn-primary" type="submit">Save</button>
    <a href="/showObjects/{{objectType}}" class="btn btn-primary" role="button">Cancel</a>
   {% else %}
    <button formaction="/updateObject/{{objectType}}/{{objectToUpdate.id}}?operation=update" class="btn btn-primary" type="submit"> Update </button>
    <button formaction="/updateObject/{{objectType}}/{{objectToUpdate.id}}?operation=delete" class="btn btn-primary" type="submit"> Delete </button>
    <a href="/showObjects/{{objectType}}" class="btn btn-primary" type="button">Cancel</a>
   {% endif %}
 </form>
 </section>
{% endblock %}

inventmanage/inventapp/templates/inventapp/saveConfirmation.html
{% extends "base.html" %}
{% block page_content %}

<div>
<a href="/showObjects/{{objectType}}" class="btn btn-primary">Show List</a>&nbsp;&nbsp;
<a href="/modelObjects/{{objectType}}" class="btn btn-primary" >Make New Entry</a><br>
</div>
<div>
	<div>
	{% if Operation == 'add' %}
	<h3> New {{objectType}} has been saved. </h3>
	Click <a href="/showObjectDetails/{{objectType}}/{{objectID}}"> here </a>  to see the record details.

	{% elif Operation == 'update' %}
	<h3> Record has been updated. </h3>
        Click <a href="/showObjectDetails/{{objectType}}/{{objectID}}"> here </a>  to see the updated record details.

	{% else %}
	<h3> Record from {{objectType}} has been deleted. </h3>

	{% endif %}
	</div>
</div>
</div>
{% endblock %}

inventmanage/inventapp/templates/inventapp/showObjectDetail.html
{% extends "base.html" %}
{% block page_content %}

<div>
<a href="/modelObjects/{{objectType}}" class="btn btn-primary" onclick="showEntry()">Make New Entry</a>&nbsp; &nbsp;
<a href="/modelObjects/{{objectType}}?edit=true&objectId={{object.id}}" class="btn btn-primary">Edit this Item</a>&nbsp; &nbsp;
<a href="/showObjects/{{objectType}}" class="btn btn-primary">Show all items</a><br>
</div>
<div>
        <div>

<h1>{{objectType}} Detail</h1>

{% for key,value in object.items %}

{% if key != "id" %}

{% if key == "fileName" %}
<b>{{key}}:</b> {{value}} <a class="documentLink" href="/displayFile/{{value}}/{{object.driveId}}" width="100%" target="_blank" >Link</a> <br>
{% else %}
<b>{{key}}:</b> {% autoescape off %}{{ value|linebreaks }}{% endautoescape %} <br>
{% endif %}


{% endif %}

{% endfor %}
   <br><br>

  </div>
</div>
</div>

{% endblock %}

inventmanage/inventapp/templates/inventapp/showObjectList.html
{% extends "base.html" %}
{% block page_content %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>

	<script>
		$(document).ready( function () {
    $('#records').DataTable();
} );
</script>

<div>
<a href="/modelObjects/{{objectType}}" class="btn btn-primary" >Make New Entry</a><br>
</div>
<div>
	<div>


	<h3> List of {{objectType}} </h3>

	{% if noEntry %}

	There is no entry to display.

	{% else %}
	<table id="records" class="display">
    <thead>
        <tr>

	{% for field in fieldNames %}
			<th> {{field}} </th>
	{% endfor %}

	</tr>
    </thead>
    <tbody>


	{% for x in objects %}
	<tr>
	{% for value in x %}
			<td>{{value}}</td>
	{% endfor %}
	<td><a href="/showObjectDetails/{{objectType}}/{{x.0}}">Show</a></td>
  <td><a href="/modelObjects/{{objectType}}?edit=true&objectId={{x.0}}">Edit</a></td>
	</tr>
	{% endfor %}

	</tbody>
</table>

{% endif %}
	</div>
</div>
</div>


        </div>


{% endblock %}